$('.owl-carousel').owlCarousel({
    items:1,
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayHoverPause:true,
    autoplayTimeout:7000,
    autoplaySpeed:1000,
    navSpeed:1000,
})
